
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'D2EFEEDA95198D418A33D672214C5F3A'
    
_lr_action_items = {'LPAR':([1,5,22,23,24,25,26,27,28,29,30,31,32,33,34,37,38,],[3,7,40,41,42,43,44,45,46,47,48,49,50,51,52,55,56,]),'SETLOCALIZATIONFIDELITY':([18,],[22,]),'CONS':([9,36,],[12,-4,]),'MOVEABS':([18,],[24,]),'DO':([14,],[18,]),'MOVE':([18,],[25,]),'STOP':([20,54,],[37,37,]),'RPAR':([8,10,15,16,19,21,58,65,66,70,71,74,96,97,98,99,100,102,103,104,116,118,123,127,],[-2,13,-3,-9,36,-8,76,83,84,88,-5,91,108,109,110,111,112,-6,114,-7,120,122,125,128,]),'MOVEABSH':([18,],[23,]),'TURNABS':([18,],[27,]),'STRING':([45,48,56,90,],[63,66,74,103,]),'MOVETO':([18,],[28,]),'RECALIBRATE':([18,],[29,]),'TURNREL':([18,],[26,]),'VISIBLE':([20,54,],[38,38,]),'SAY':([18,],[30,]),'NUM':([7,17,40,41,42,43,44,46,47,49,50,51,52,53,55,57,77,78,79,80,81,82,85,86,87,89,92,105,106,107,113,119,121,126,],[11,21,58,59,60,61,62,64,65,67,68,69,70,71,73,75,93,94,95,96,97,98,99,100,101,102,104,115,116,117,118,123,124,127,]),'COMMA':([4,11,36,59,60,61,62,63,64,67,68,69,73,93,94,95,101,115,117,124,],[6,14,-4,77,78,79,80,81,82,85,86,87,90,105,106,107,113,119,121,126,]),'THEN':([35,39,72,76,83,84,88,91,108,109,110,111,112,114,120,122,125,128,],[53,57,89,-21,-20,-11,-19,-23,-17,-16,-12,-13,-18,-24,-14,-15,-22,-10,]),'$end':([2,13,],[0,-1,]),'LOCATE':([18,],[31,]),'END':([14,],[16,]),'GOTO':([14,],[17,]),'ELSE':([75,],[92,]),'P':([0,],[1,]),'V':([3,6,12,],[5,5,5,]),'FORWARD':([18,],[32,]),'UNTIL':([35,76,83,84,88,108,109,110,111,112,120,122,125,128,],[54,-21,-20,-11,-19,-17,-16,-12,-13,-18,-14,-15,-22,-10,]),'IF':([14,],[20,]),'MOVEREL':([18,],[33,]),'NIL':([6,12,],[8,8,]),'CHARGE':([18,],[34,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'vertex':([3,6,12,],[4,9,9,]),'vertices':([6,12,],[10,15,]),'content':([14,],[19,]),'cnd':([20,54,],[39,72,]),'program':([0,],[2,]),'action':([18,],[35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> P LPAR vertex COMMA vertices RPAR','program',6,'p_program','parserIG.py',53),
  ('vertices -> NIL','vertices',1,'p_vertices','parserIG.py',57),
  ('vertices -> vertex CONS vertices','vertices',3,'p_vertices','parserIG.py',58),
  ('vertex -> V LPAR NUM COMMA content RPAR','vertex',6,'p_vertex','parserIG.py',65),
  ('content -> DO action THEN NUM','content',4,'p_content','parserIG.py',71),
  ('content -> DO action UNTIL cnd THEN NUM','content',6,'p_content','parserIG.py',72),
  ('content -> IF cnd THEN NUM ELSE NUM','content',6,'p_content','parserIG.py',73),
  ('content -> GOTO NUM','content',2,'p_content','parserIG.py',74),
  ('content -> END','content',1,'p_content','parserIG.py',75),
  ('action -> MOVE LPAR NUM COMMA NUM COMMA NUM COMMA NUM COMMA NUM RPAR','action',12,'p_action','parserIG.py',98),
  ('action -> SAY LPAR STRING RPAR','action',4,'p_action','parserIG.py',99),
  ('action -> MOVETO LPAR NUM COMMA NUM RPAR','action',6,'p_action','parserIG.py',100),
  ('action -> LOCATE LPAR NUM COMMA NUM RPAR','action',6,'p_action','parserIG.py',101),
  ('action -> MOVEABS LPAR NUM COMMA NUM COMMA NUM RPAR','action',8,'p_action','parserIG.py',102),
  ('action -> MOVEREL LPAR NUM COMMA NUM COMMA NUM RPAR','action',8,'p_action','parserIG.py',103),
  ('action -> TURNABS LPAR STRING COMMA NUM RPAR','action',6,'p_action','parserIG.py',104),
  ('action -> TURNREL LPAR NUM COMMA NUM RPAR','action',6,'p_action','parserIG.py',105),
  ('action -> FORWARD LPAR NUM COMMA NUM RPAR','action',6,'p_action','parserIG.py',106),
  ('action -> CHARGE LPAR NUM RPAR','action',4,'p_action','parserIG.py',107),
  ('action -> RECALIBRATE LPAR NUM RPAR','action',4,'p_action','parserIG.py',108),
  ('action -> SETLOCALIZATIONFIDELITY LPAR NUM RPAR','action',4,'p_action','parserIG.py',109),
  ('action -> MOVEABSH LPAR NUM COMMA NUM COMMA NUM COMMA NUM RPAR','action',10,'p_action','parserIG.py',110),
  ('cnd -> VISIBLE LPAR STRING RPAR','cnd',4,'p_cnd','parserIG.py',140),
  ('cnd -> STOP LPAR NUM COMMA STRING RPAR','cnd',6,'p_cnd','parserIG.py',141),
]
