
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '613AD8050594F38E56FCC0657C1D6055'
    
_lr_action_items = {'LPAR':([1,5,22,23,24,25,26,27,28,30,32,33,],[3,7,35,36,37,38,39,40,41,44,45,46,]),'CONS':([9,31,],[12,-4,]),'MOVEABS':([18,],[25,]),'DO':([14,],[18,]),'MOVE':([18,],[26,]),'STOP':([20,43,],[32,32,]),'RPAR':([8,10,15,16,19,21,53,55,59,73,74,78,79,80,81,82,91,92,99,],[-2,13,-3,-9,31,-8,66,-5,71,83,84,88,-6,89,90,-7,94,95,100,]),'TURNABS':([18,],[30,]),'STRING':([40,44,46,70,],[53,57,59,81,]),'MOVETO':([18,],[23,]),'TURNREL':([18,],[28,]),'VISIBLE':([20,43,],[33,33,]),'SAY':([18,],[27,]),'NUM':([7,17,35,36,37,38,39,41,42,45,47,61,62,63,64,65,67,68,69,72,85,86,87,96,98,],[11,21,48,49,50,51,52,54,55,58,60,73,74,75,76,77,78,79,80,82,91,92,93,97,99,]),'COMMA':([4,11,31,48,49,50,51,52,54,57,58,75,76,77,93,97,],[6,14,-4,61,62,63,64,65,67,69,70,85,86,87,96,98,]),'THEN':([29,34,56,66,71,83,84,88,89,90,94,95,100,],[42,47,68,-11,-18,-13,-12,-17,-16,-19,-15,-14,-10,]),'$end':([2,13,],[0,-1,]),'LOCATE':([18,],[22,]),'END':([14,],[16,]),'GOTO':([14,],[17,]),'ELSE':([60,],[72,]),'P':([0,],[1,]),'V':([3,6,12,],[5,5,5,]),'UNTIL':([29,66,83,84,88,89,94,95,100,],[43,-11,-13,-12,-17,-16,-15,-14,-10,]),'IF':([14,],[20,]),'MOVEREL':([18,],[24,]),'NIL':([6,12,],[8,8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'vertex':([3,6,12,],[4,9,9,]),'vertices':([6,12,],[10,15,]),'content':([14,],[19,]),'cnd':([20,43,],[34,56,]),'program':([0,],[2,]),'action':([18,],[29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> P LPAR vertex COMMA vertices RPAR','program',6,'p_program','parserIG.py',53),
  ('vertices -> NIL','vertices',1,'p_vertices','parserIG.py',57),
  ('vertices -> vertex CONS vertices','vertices',3,'p_vertices','parserIG.py',58),
  ('vertex -> V LPAR NUM COMMA content RPAR','vertex',6,'p_vertex','parserIG.py',65),
  ('content -> DO action THEN NUM','content',4,'p_content','parserIG.py',71),
  ('content -> DO action UNTIL cnd THEN NUM','content',6,'p_content','parserIG.py',72),
  ('content -> IF cnd THEN NUM ELSE NUM','content',6,'p_content','parserIG.py',73),
  ('content -> GOTO NUM','content',2,'p_content','parserIG.py',74),
  ('content -> END','content',1,'p_content','parserIG.py',75),
  ('action -> MOVE LPAR NUM COMMA NUM COMMA NUM COMMA NUM COMMA NUM RPAR','action',12,'p_action','parserIG.py',98),
  ('action -> SAY LPAR STRING RPAR','action',4,'p_action','parserIG.py',99),
  ('action -> MOVETO LPAR NUM COMMA NUM RPAR','action',6,'p_action','parserIG.py',100),
  ('action -> LOCATE LPAR NUM COMMA NUM RPAR','action',6,'p_action','parserIG.py',101),
  ('action -> MOVEABS LPAR NUM COMMA NUM COMMA NUM RPAR','action',8,'p_action','parserIG.py',102),
  ('action -> MOVEREL LPAR NUM COMMA NUM COMMA NUM RPAR','action',8,'p_action','parserIG.py',103),
  ('action -> TURNABS LPAR STRING COMMA NUM RPAR','action',6,'p_action','parserIG.py',104),
  ('action -> TURNREL LPAR NUM COMMA NUM RPAR','action',6,'p_action','parserIG.py',105),
  ('cnd -> VISIBLE LPAR STRING RPAR','cnd',4,'p_cnd','parserIG.py',124),
  ('cnd -> STOP LPAR NUM COMMA STRING RPAR','cnd',6,'p_cnd','parserIG.py',125),
]
