# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  ## For headless comment above line and uncomment below one
  #config.vm.box = "ubuntu/trusty64"
  #config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", ip: "192.168.33.20"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.name = "cmu-mars"
  end

 $script = <<-SCRIPT
  sudo apt-get install software-properties-common -y --force-yes
  sudo apt-add-repository ppa:ansible/ansible -y 
  sudo apt-get update -y
  sudo apt-get install ansible -y --force-yes
  sudo apt-get install -f
  sudo cp /vagrant/ros-latest.list /etc/apt/sources.list.d/
  cd /vagrant
  sudo ansible-playbook turtle.yml
  echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc
  source ~/.bashrc
  source /opt/ros/indigo/setup.bash
  sudo rosdep init
  sudo rosdep fix-permissions
  rosdep update
  sudo cp /vagrant/tcpros_service.py /opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/
  sudo add-apt-repository ppa:openjdk-r/ppa
  sudo apt-get update
  sudo apt-get install openjdk-8-jre-headless -y --force-yes
  sudo apt-get install xserver-xorg-video-dummy
  SCRIPT

  config.vm.provision "shell", inline: $script, privileged: false
  
  config.vm.provision "shell" do |s|
    s.inline = "cp -r /vagrant/catkin_ws /home/vagrant"
	s.name = "Copy the base programs for CP1"
	s.privileged = false
  end
  
   config.vm.provision "shell" do |s|
    s.inline = "cp /vagrant/setup-cp1.sh /home/vagrant"
	s.name = "Copy the setup script"
	s.privileged = false
  end
  
   config.vm.provision "shell" do |s|
    s.inline = "cp -r /vagrant/run-cp1.sh /home/vagrant"
	s.name = "Copy the CP1 run script"
	s.privileged = false
  end
  
  config.vm.provision "shell" do |s|
    s.inline = "cp -r /vagrant/xorg.conf /home/vagrant"
	s.name = "Copy the X config file for use by headless robot"
	s.privileged = false
  end
  
  $setup = <<-SETUP
  echo Setting up challenge problem 1
  ./setup-cp1.sh
  echo "source catkin_ws/devel/setup.bash" >> .bashrc
  SETUP
  
  config.vm.provision "shell", inline: $setup, privileged: false
  
end
