# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
#  config.vm.box_version = "=20160802.0.1"
  ## For headless comment above line and uncomment below one
  #config.vm.box = "ubuntu/trusty64"
  #config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "private_network", ip: "192.168.33.20"

  ## the BRASSCOMMS layer runs on 5000; this allows you to access it from
  ## outside the guest machine, which is convenient.
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.name = "cmu-mars"
    vb.cpus = 2
  end

 $script = <<-SCRIPT
  sudo apt-get install software-properties-common -y --force-yes
  sudo apt-add-repository ppa:ansible/ansible -y
  sudo add-apt-repository ppa:openjdk-r/ppa
  sudo sh -c 'echo "deb file:/vagrant/debs ./" >> /etc/apt/sources.list'
  sudo apt-get update -y
  sudo apt-get install ansible -y --force-yes
  sudo apt-get install -f
##  sudo apt-get install dpkg-dev -y --force-yes
  sudo apt-get install openjdk-8-jre-headless -y --force-yes
  sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure ## per https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1396760
  cd /vagrant
  sudo ansible-playbook turtle.yml
  echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc
  source ~/.bashrc
  source /opt/ros/indigo/setup.bash
  sudo rosdep init
  sudo rosdep fix-permissions
  rosdep update
  sudo cp /vagrant/tcpros_service.py /opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/
  sudo apt-get update
  sudo apt-get install xserver-xorg-video-dummy
  sudo apt-get -y install python-flask
  sudo apt-get -y install python-enum
  # overcome webcam issue
  sudo ln -s /dev/null /dev/raw1394
  sudo apt-get -y install emacs
  SCRIPT



  config.vm.provision "shell", inline: $script, privileged: false

  config.vm.provision "shell" do |s|
    s.inline = "cp -r /vagrant/catkin_ws /home/vagrant"
	s.name = "Copy the base programs for CP1"
	s.privileged = false
  end

   config.vm.provision "shell" do |s|
    s.inline = "cp /vagrant/setup-cp1.sh /home/vagrant; chmod +x /home/vagrant/setup-cp1.sh"
	s.name = "Copy the setup script"
	s.privileged = false
  end

   config.vm.provision "shell" do |s|
    s.inline = "cp /vagrant/run-cp1.sh /home/vagrant; chmod +x /home/vagrant/run-cp1.sh"
	s.name = "Copy the CP1 run script"
	s.privileged = false
  end

  config.vm.provision "shell" do |s|
    s.inline = "cp /vagrant/xorg.conf /home/vagrant"
	s.name = "Copy the X config file for use by headless robot"
	s.privileged = false
  end

  $setup = <<-SETUP

  echo Setting up challenge problem 1
  ./setup-cp1.sh
  echo "source catkin_ws/devel/setup.bash" >> .bashrc
  SETUP

  config.vm.provision "shell", inline: $setup, privileged: false

end
